version: "3"
services:
  db-loc:
    image: "postgres:13"
    container_name: "swam-data"
    env_file:
      db.env
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  swam_db_loc